# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/apptainer:latest'
  - '.'

# Build and push the lolcow.sif image
- name: 'gcr.io/$PROJECT_ID/apptainer:latest' # Use the newly built apptainer image
  args:
  - 'build'
  - '--fakeroot'
  - 'lolcow.sif'
  - 'lolcow.def'
- name: 'gcr.io/$PROJECT_ID/apptainer:latest'
  args:
  - 'push'
  - 'lolcow.sif'
  - 'oras://${_LOCATION}/$PROJECT_ID/${_REPOSITORY}/lolcow:${_VERSION}'
substitutions:
  _LOCATION: us-docker.pkg.dev
  _REPOSITORY: sifs
  _VERSION: latest

# You can remove this if you don't need the apptainer image separately
images:
- 'gcr.io/$PROJECT_ID/apptainer:latest'
tags: ['cloud-builders-community']
