# cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/apptainer:latest'
  - '.'
  id: 'build-apptainer' # Add an ID to this step

# Build and push the lolcow.sif image (only if 'build-apptainer' step runs)
- name: 'gcr.io/$PROJECT_ID/apptainer:latest' 
  args:
  - 'build'
  - '--fakeroot'
  - 'lolcow.sif'
  - 'lolcow.def'
  waitFor: ['-', 'build-apptainer'] # Wait for success or execution of 'build-apptainer'

- name: 'gcr.io/$PROJECT_ID/apptainer:latest'
  args:
  - 'push'
  - 'lolcow.sif'
  - 'oras://${_LOCATION}/$PROJECT_ID/${_REPOSITORY}/lolcow:${_VERSION}'
  waitFor: ['-', 'build-apptainer'] # Wait for success or execution of 'build-apptainer'

substitutions:
  _LOCATION: us-docker.pkg.dev
  _REPOSITORY: sifs
  _VERSION: latest

# You can remove this if you don't need the apptainer image separately
images:
- 'gcr.io/$PROJECT_ID/apptainer:latest'
tags: ['cloud-builders-community']

